# **Semantic Textual Similarity**

In [210]:
#!pip install nltk
#!pip install allennlp
#!pip install pytorch_transformers
#!pip install seaborn
#!pip install simpletransformers
#!pip install pytorch_pretrained_bert

In [188]:
import scipy
import nltk
nltk.download('punkt')
import tarfile
from nltk.tokenize import word_tokenize
from allennlp import *
import torch
from pytorch_transformers import *
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from transformers import GPT2Tokenizer, GPT2Model, GPT2LMHeadModel
from transformers import AutoTokenizer 
from transformers import AutoModelForPreTraining  
from transformers import AutoModel 
from simpletransformers.language_representation import RepresentationModel
import numpy as np
from sentence_transformers import SentenceTransformer, util

[nltk_data] Downloading package punkt to /home/jovyan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [279]:
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

In [280]:
model = GPT2LMHeadModel.from_pretrained('gpt2')

In [305]:
sentences_1 = 'Uma mulher está dançando na chuva'

In [306]:
sentences_1

'Uma mulher está dançando na chuva'

In [307]:
sentences_2 = 'Uma mulher está dançando na sala'

In [308]:
sentences_2

'Uma mulher está dançando na sala'

In [309]:
sentences_1_split = sentences_1.split()

In [310]:
sentences_2_split = sentences_2.split()

In [311]:
sentences1 = sentences_1_split

In [312]:
sentences1

['Uma', 'mulher', 'está', 'dançando', 'na', 'chuva']

In [313]:
sentences2 = sentences_2_split

In [314]:
sentences2

['Uma', 'mulher', 'está', 'dançando', 'na', 'sala']

In [316]:
embeddings1 = torch.Tensor(sentences1)

ValueError: too many dimensions 'str'

In [ ]:
embeddings2 = torch.tensor(sentences2)

In [291]:
embeddings_1

tensor([50256.])

In [292]:
embeddings_2

tensor([50256.])

In [293]:
embeddings1 = torch.tensor([tokenizer.convert_tokens_to_ids(embeddings_1)])

In [294]:
embeddings1

tensor([[50256]])

In [218]:
cosine_scores = util.cos_sim(embeddings1, embeddings2)

In [209]:
#Output the pairs with their score
for i in range(len(sentences1)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i], sentences2[i], cosine_scores[i][i]))

Uma mulher está dançando na chuva 		 Uma mulher está dançando na sala 		 Score: 1.0000


In [ ]:
def score(sentence):
    tokenize_input = tokenizer.tokenize(sentence)
    tensor_input = torch.tensor([tokenizer.convert_tokens_to_ids(tokenize_input)])
    loss=model(tensor_input, lm_labels=tensor_input)
    return math.exp(loss)
